sudo: required
dist: xenial
services:
- docker
install:
- docker build -t test .
script:
- docker run -ti test /bin/true
- docker run -ti test pkgforge --help
notifications:
  email: false
  slack:
    secure: HebWFXB6ddaB0+pUDQj+0HiuCoCOt6dLWBqbKwgCMhslpNvCo0er4/cV30TedBESdYM5vjknn3ajBm3vtkFwwMketywHOCqXIPNMkGhnwNAc1b4fLYMSJ6Nu3SpeSPf1p/hwlk4gBlds86jidbCrt9yVl8ZnvScPQsAxmftjgQzTAfsFbV2nNrQfrBwT4CAbOHHga7uvZ2w7Vy6I3T1dSGORiixV6G3scWG2P3P/R2J9uMoOOeFbakUNT4M+W7B5uAxXk2VqMKOt811wMTmgNI/72StumQJ46nJows6X1LyVQMlspbdUKctYwWe/cZ8f2WNro7FPG/+kcRV5o23jxjYeMN2eHYmZs0FvQoPpdj90f2NRf1TvZk53uBYZtplclzzVPXi+CbhWFfc6I1S/s0cZzNPb+3Z+Kvv4WTkZLt/3DgKTKAqyvote/qeNFa6SXKhWp2Zu/VZExxmE6Z/g1rGsFZLgfwCUNVDyCI+BqupLI5B030RIe+5Nt9CoCyh+gqqwxCbIz9tlJ6Mw2jQGYz2cR1dHepnQQQSwJnah0R6/ewrsHBY4VtgzwKsN8xOS65MG5JPx1xnTuZxhY+4xXZWn/l3uKf7qmQ+3CylVS8g/wYL/RGio2x82bK4jGrEv+Fy7xLjuQfsHJnucgJhuRS1wDAr650WtTDBztqzH+sI=
